# Generated by Django 5.0.6 on 2024-07-25 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0002_orden_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='order_id',
            new_name='orden_id',
        ),
    ]
